#
# https://docs.spring.io/spring-boot/docs/current/reference/html/howto-properties-and-configuration.html
#
spring:
  profiles: profile2
refdata:
  solace:
    queue: 'jms:queue:rmg_cmprsk_mktrsk_refdata_queue'
  consumer:
  - key: employee
    table: 'common.dbo.employee'
